[package]
name = "excel"
version = "0.1.0"
authors = ["wk30 <foo_stacker@yeah.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
calamine = "0.16.2"
glob = "0.3.0"
