[package]
name = "sea-orm-demo"
version = "0.1.0"
edition = "2024"

[workspace]
members = [".", "api", "service", "entity", "migration", "middleware"]

[dependencies]
actix-example-api = { path = "api" }
