# edition = "2018"
# newline_style = "Unix"
# comments
# normalize_comments = true
# wrap_comments = true
# imports

newline_style = "Unix"
reorder_imports = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
