[package]
name = "schemars-demo"
version = "0.1.0"
edition = "2021"

# [lib]
# proc-macro = true

[dependencies]
serde_json = "1.0.132"
schemars = { version = "1.0.0-alpha.15" }
serde = { version = "1.0.215", features = ["derive"] }
syn = "2.0.87"
quote = "1.0.37"
