[package]
name = "inner-arc"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
dashmap = "6.1"
strum = "0.26"
strum_macros = "0.26"
tokio = { version = "1.42", features = ["full"] }
